name: generate images

on:
 push:
   branches: ["main"]

jobs:
  thumGen:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Process videos
        id: processVideos
        run: curl --location 'https://overpass-api.de/api/interpreter' --header 'Content-Type:text/plain' --data '[out:json][timeout:180];area(3600059470)->.brazil;(node["OBTC"="UAIBIT"](area.brazil););out body;>;out skel qt;' | jq -r '.elements[] |"## \(.tags.name // "Unnamed Location")\n" +"**Type:** \(.type)\n" +"**ID:** \(.id)\n" +"**Coordinates:** [\(.lat), \(.lon)]\n" +(if .tags["addr:street"] then "**Address:** \(.tags["addr:street"]) \(.tags["addr:housenumber"] // ""), \(.tags["addr:suburb"] // ""), \(.tags["addr:city"] // ""), \(.tags["addr:postcode"] // "")\n" else "" end) +(to_entries | map(select(.key | test("^tags$")).[].tags) | .[] | to_entries[] | select(.key | test("^(name|addr:|payment:|currency:|amenity|shop|phone|website|description|opening_hours|diet:|CBTC|OBTC)")) | "- **\(.key):** \(.value)") | join("\n") > output.md 
