name: generate images

on:
 push:
   branches: ["main"]

jobs:
  thumGen:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Process videos
        id: processVideos
        run: curl --location 'https://overpass-api.de/api/interpreter' \ --header 'Content-Type:text/plain' \ --data '[out:json][timeout:180];area(3600059470)->.brazil;(node["OBTC"="UAIBIT"](area.brazil););out body;>;out skel qt;'
